### ISSUE TITLE
IP in macvlan is not reachable from diskstation and not from OpenVPN

### ISSUE THREAD

**Issue by winkler-winsen** [piwi3910/techtalk#6]
Macvlan works well in LAN. But not inside the Diskstation terminal and so it's not useable with VPN Server package (e.g. OpenVPN)

Cannot ping the IP (or reach services), when in terminal of Diskstation.
Cannot ping the IP (or reach services), when connected from outside via VPN Server (e.g. OpenVPN)

Refferring to [07 Pi-hole on Synology Docker](https://github.com/piwi3910/techtalk/tree/master/Docker_series/07)

**Comment by winkler-winsen** [comment]
Solved!

Create a new device MACVLAN bridge and add IPs. This have to be done every time after startup.

Put this into DSM Task Scheduler to run at every startup:
```bash
#!/bin/sh

#Set timeout to wait host network is up and running
sleep 60

#Host macvlan bridge recreate
ip link add macvlan-br0 link ovs_bond0 type macvlan mode bridge # see ifconfig / Interface Name "ovs_bond0" or normally "eth0"
ip addr add 192.168.178.99/32 dev macvlan-br0 # IP of NAS running Docker
ip link set macvlan-br0 up
ip route add 192.168.178.254/32 dev macvlan-br0 # IP of Pi-hole Docker Container inside MACVLAN
```

`macvlan-br0`: just a name for this bridge
`ovs_bond0`: Interface name of LAN. Please see `ifconfig`. In my case I have a LAN Bond. Normally this should be `eth0` 
`192.168.178.99/32`: IP and Subnet (in CIDR notation) of Synology NAS where Docker runs
`192.168.178.254/32`: IP and Subnet (in CIDR notation) of Docker Container running Pi-hole via MACVLAN

Credits: https://community.synology.com/enu/forum/15/post/120118?page=2&sort=oldest

**Comment by D3rSchurk3** [comment]
My configuration for DSM7 since the task scheduler can't be used anymore to run tasks at startup:

1. "cd /usr/local/lib/systemd/system" 
2. "nano pkg-macvlan-bridge.service" (requires SynoCli File Tools)
3. Create startup script
4. "systemctl start pkg-macvlan-bridge.service"
5. "systemctl enable pkg-macvlan-bridge.service"

Startup script:

[Unit]
Description=create macvlan bridge
Wants=network-online.target
After=network.target network-online.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
ExecStart=/bin/bash -c "ip link add macvlan-br0 link ovs_eth0 type macvlan mode bridge && ip addr add 192.168.1.115/32 dev macvlan-br0 && ip link set macvlan-br0 up && ip route add 192.168.1.116/32 dev macvlan-br0 && ip route add 192.168.1.117/32 dev macvlan-br0 && ip route add 192.168.1.118/32 dev macvlan-br0 && ip route add 192.168.1.119/32 dev macvlan-br0 && ip route add 192.168.1.120/32 dev macvlan-br0"

**Comment by winkler-winsen** [comment]
Why can't Task Scheduler run startup tasks anymore?

![grafik](https://user-images.githubusercontent.com/43114182/139595898-c16f0d9a-7135-4031-babb-5b2a6b57e9aa.png)

![grafik](https://user-images.githubusercontent.com/43114182/139595865-66a4abd2-ef25-47e2-84f9-604bf5a92805.png)

DSM 7.0.1-42218
